### ISSUE TITLE
CCNxTxRxRelay should not harcode user name/user dir

### ISSUE THREAD

**Issue by truedat101** [RazortoothRTC/ccnx#27]
Fix this so that the first run creates the proper user dir and a default keystore if needed.  We need this for the ccndcontrol command to work properly on Android.

**Comment by truedat101** [comment]
In #24 I implemented the default forwarding entries, but hacked in the user dir and keystore, because the ccndcontrol util needs it.  Need to see if there is a way to work around this particular issue.

**Comment by truedat101** [comment]
In line 326 of CCNHandle, we call open(), no args.  This requires the keystore and user HOME to be set.  This won't be the case on Android, not under normal circumstances.

**Comment by truedat101** [comment]
We can call CCNHandle.open() with a KeyManager.

**Comment by truedat101** [comment]
Here is the error we get otherwise:

I/ccnx.Default(27500): java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] org.ccnx.ccn.protocol.PublisherPublicKeyDigest.digest()' on a null object reference
I/ccnx.Default(27500):  at org.ccnx.ccn.impl.security.keys.BasicKeyManager.getDefaultSigningKey(BasicKeyManager.java:994)
I/ccnx.Default(27500):  at org.ccnx.ccn.protocol.ContentObject.buildContentObject(ContentObject.java:267)
I/ccnx.Default(27500):  at org.ccnx.ccn.protocol.ContentObject.buildContentObject(ContentObject.java:285)
I/ccnx.Default(27500):  at org.ccnx.ccn.profiles.ccnd.CCNDaemonHandle.sendIt(CCNDaemonHandle.java:87)
I/ccnx.Default(27500):  at org.ccnx.ccn.profiles.ccnd.FaceManager.sendIt(FaceManager.java:368)
I/ccnx.Default(27500):  at org.ccnx.ccn.profiles.ccnd.FaceManager.createFace(FaceManager.java:350)
I/ccnx.Default(27500):  at org.ccnx.ccn.profiles.ccnd.FaceManager.createFace(FaceManager.java:337)
I/ccnx.Default(27500):  at org.ccnx.ccn.utils.ccndcontrol.executeCommand(ccndcontrol.java:329)
I/ccnx.Default(27500):  at org.ccnx.android.ccnlib.CCNxServiceControl.configureDefaultRoutes(CCNxServiceControl.java:373)
I/ccnx.Default(27500):  at org.ccnx.android.ccnlib.CCNxServiceControl$AsyncDefaultForwardingConfigTask.doInBackground(CCNxServiceControl.java:325)
I/ccnx.Default(27500):  at org.ccnx.android.ccnlib.CCNxServiceControl$AsyncDefaultForwardingConfigTask.doInBackground(CCNxServiceControl.java:321)
I/ccnx.Default(27500):  at android.os.AsyncTask$2.call(AsyncTask.java:288)
I/ccnx.Default(27500):  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
I/ccnx.Default(27500):  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
I/ccnx.Default(27500):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
I/ccnx.Default(27500):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
I/ccnx.Default(27500):  at java.lang.Thread.run(Thread.java:811)

**Comment by truedat101** [comment]
Struggling a bit with the basic KeyManager.  I can get an instance and try  to get the one for the CCND keystore.  However, can't verify signer (CCND throws an error)....

**Comment by truedat101** [comment]
Can't seem to get these changes to work.  Back out the change and go with a new default admin user "ccndadmin", with storage of keystore in internal storage.

**Comment by truedat101** [comment]
Fixed, closing.  We should revisit putting the configuration settings for ccndadmin user into prefs.
