### ISSUE TITLE
CCNxTxRxRelay Fix NPTR crash on adding default routes

### ISSUE THREAD

**Issue by truedat101** [RazortoothRTC/ccnx#30]
W/ccnx.Default(21446): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.matches(java.lang.String)' on a null object reference
W/ccnx.Default(21446):  at org.ccnx.ccn.config.PlatformConfiguration.<clinit>(PlatformConfiguration.java:65)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.security.crypto.util.SignatureHelper.verify(SignatureHelper.java:198)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.security.crypto.CCNSignatureHelper.verify(CCNSignatureHelper.java:229)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.security.crypto.CCNSignatureHelper.verify(CCNSignatureHelper.java:250)
W/ccnx.Default(21446):  at org.ccnx.ccn.protocol.ContentObject.verify(ContentObject.java:662)
W/ccnx.Default(21446):  at org.ccnx.ccn.protocol.ContentObject.verify(ContentObject.java:596)
W/ccnx.Default(21446):  at org.ccnx.ccn.protocol.ContentObject.verify(ContentObject.java:626)
W/ccnx.Default(21446):  at org.ccnx.ccn.protocol.ContentObject.verify(ContentObject.java:539)
W/ccnx.Default(21446):  at org.ccnx.ccn.protocol.ContentObject$SimpleVerifier.verify(ContentObject.java:124)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.CCNNetworkManager.fetchCCNDId(CCNNetworkManager.java:1414)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.CCNNetworkManager.getCCNDId(CCNNetworkManager.java:778)
W/ccnx.Default(21446):  at org.ccnx.ccn.profiles.ccnd.PrefixRegistrationManager.selfRegisterPrefix(PrefixRegistrationManager.java:409)
W/ccnx.Default(21446):  at org.ccnx.ccn.profiles.ccnd.PrefixRegistrationManager.selfRegisterPrefix(PrefixRegistrationManager.java:395)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.CCNNetworkManager.registerPrefix(CCNNetworkManager.java:1067)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.CCNNetworkManager.setInterestFilter(CCNNetworkManager.java:1026)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.CCNNetworkManager.setInterestFilter(CCNNetworkManager.java:966)
W/ccnx.Default(21446):  at org.ccnx.ccn.CCNHandle.registerFilter(CCNHandle.java:376)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.CCNFlowControl.addNameSpace(CCNFlowControl.java:206)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.security.keys.KeyServer.serveKey(KeyServer.java:103)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.security.keys.BasicKeyManager.serveKey(BasicKeyManager.java:248)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.security.keys.BasicKeyManager.publishKey(BasicKeyManager.java:1143)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.security.keys.BasicKeyManager.initializeKeyServer(BasicKeyManager.java:230)
W/ccnx.Default(21446):  at org.ccnx.ccn.impl.security.keys.BasicKeyManager.initialize(BasicKeyManager.java:219)
W/ccnx.Default(21446):  at org.ccnx.ccn.KeyManager.createDefaultKeyManager(KeyManager.java:153)
W/ccnx.Default(21446):  at org.ccnx.ccn.KeyManager.getDefaultKeyManager(KeyManager.java:115)
W/ccnx.Default(21446):  at org.ccnx.ccn.CCNHandle.<init>(CCNHandle.java:186)
W/ccnx.Default(21446):  at org.ccnx.ccn.CCNHandle.open(CCNHandle.java:86)
W/ccnx.Default(21446):  at org.ccnx.ccn.utils.ccndcontrol.executeCommand(ccndcontrol.java:342)
W/ccnx.Default(21446):  at org.ccnx.ccn.utils.ccndcontrol.executeCommand(ccndcontrol.java:271)
W/ccnx.Default(21446):  at org.ccnx.android.ccnlib.CCNxServiceControl.configureDefaultRoutes(CCNxServiceControl.java:408)
W/ccnx.Default(21446):  at org.ccnx.android.ccnlib.CCNxServiceControl$AsyncDefaultForwardingConfigTask.doInBackground(CCNxServiceControl.java:330)
W/ccnx.Default(21446):  at org.ccnx.android.ccnlib.CCNxServiceControl$AsyncDefaultForwardingConfigTask.doInBackground(CCNxServiceControl.java:326)
W/ccnx.Default(21446):  at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/ccnx.Default(21446):  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/ccnx.Default(21446):  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/ccnx.Default(21446):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/ccnx.Default(21446):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/ccnx.Default(21446):  at java.lang.Thread.run(Thread.java:811)

**Comment by truedat101** [comment]
First run (after install) is fine, but subsequent runs it will always crash this way.  Need to determine if we've got some default values lurking around here that are mishandled somehow.

**Comment by truedat101** [comment]
Hmm, odd behavior.  Must be a problem with the keystore creation, and we can't verify content objects on subsequent runs because perhaps the keystore initialization didn't happen properly.  Need to fix that.

**Comment by truedat101** [comment]
Can't seem to reproduce this right now on my Nexus 7, Android 4.4, running CCNxTxRxRelay 0.7.2-wip-b10 .
