### ISSUE TITLE
CCNx Android Services fail to move from Stopped to Running  after being manually stopped after running overnight

### ISSUE THREAD

**Issue by truedat101** [RazortoothRTC/ccnx#5]
We are in "Running", hit stop all, and then go to stopped.  Can't start after this point, as we end up in "Finished" state.  Related to #4 .

**Comment by truedat101** [comment]
Verified that once we get into this state there is no way out.  If we hit start, from stopped, we end up in SERVICE_FINISHED .

**Comment by truedat101** [comment]
Found that

```

W/ContextImpl( 2324): Implicit intents with startService are not safe: Intent { act=org.ccnx.android.service.ccnd.SERVICE } android.content.ContextWrapper.bindService:517 org.ccnx.android.ccnlib.CCNxWrapper.bindService:155 org.ccnx.android.ccnlib.CCNxWrapper.startService:107 
W/ContextImpl( 2324): Implicit intents with startService are not safe: Intent { act=org.ccnx.android.service.repo.SERVICE } android.content.ContextWrapper.bindService:517 org.ccnx.android.ccnlib.CCNxWrapper.bindService:155 org.ccnx.android.ccnlib.CCNxWrapper.startService:107 


```

**Comment by truedat101** [comment]
Also, see:

```

E/ActivityThread( 2324):    at org.ccnx.android.ccnlib.CCNxServiceControl.startAll(CCNxServiceControl.java:145)
E/ActivityThread( 2324):    at org.ccnx.android.ccnlib.CCNxServiceControl$3.run(CCNxServiceControl.java:172)


```

**Comment by truedat101** [comment]
Looks like one can also get CCND status to SERVICE_RUNNING and still have Repo Status : SERVICE_FINISHED

**Comment by truedat101** [comment]
When it works well, here is what you should see:

```

I/CCNxServiceControl(17222): startAll waiting for REPO waitForReady
I/CCNxServiceControl(17222): repoCallback repoStatus = SERVICE_INITIALIZING
D/CCNxServiceControl(17222): newCCNxAPIStatus sending REPO_INITIALIZING
D/CCNxServiceControl(17222): newCCNxAPIStatus sending START_ALL_REPO_DONE
D/CCNxServiceControl(17222): newCCNxAPIStatus sending START_ALL_DONE
I/CCNxServiceControl(17222): repoCallback repoStatus = SERVICE_RUNNING
D/CCNxServiceControl(17222): newCCNxAPIStatus sending REPO_RUNNING

```

**Comment by truedat101** [comment]
Verified that the call to CCNxWrapper.startService()/bindService() is where the "overnight" failure occurs, which gets hit each time we call ccndInterface.startService() and repoInterface.startService().  Need to focus on this as to why the exceptions occur.

**Comment by truedat101** [comment]
Funny, with the fix for #6, there doesn't seem to be a problem with the services getting into crashed state.  Needs more testing.  Leave this open.
