### ISSUE TITLE
CCNx Android Services leak context on view orientation change

### ISSUE THREAD

**Issue by truedat101** [RazortoothRTC/ccnx#6]
See error that gets thrown:

```
E/ActivityThread( 2324): android.app.ServiceConnectionLeaked: Activity org.ccnx.android.services.Controller has leaked ServiceConnection org.ccnx.android.ccnlib.CCNxWrapper$2@6516ff10 that was originally bound here
E/ActivityThread( 2324):    at org.ccnx.android.ccnlib.CCNxWrapper.bindService(CCNxWrapper.java:155)
E/ActivityThread( 2324):    at org.ccnx.android.ccnlib.CCNxWrapper.startService(CCNxWrapper.java:107)

```

**Comment by truedat101** [comment]
We don't really need orientation support, so we should suppress it.  Otherwise, we try to rebind without unbinding (I think it happens in onCreate).

**Comment by truedat101** [comment]
This is a fairly easy problem to fix.  I'd rather know why orientations changes create an unstable situation, however, this may be because we leave something bound in the view which doesn't get released before the view changes.  This may create unstable scenarios when onCreate is called again.

**Comment by truedat101** [comment]
After some testing, this new configuration seems a lot more stable, and I've had trouble getting it to crash or get into a nasty state.

**Comment by truedat101** [comment]
Mark as fixed.
